#!/usr/bin/env bash
# Checks for the command line arguments

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning paramentals

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Stop strict host key from checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"


# Checking if the file transfered was successful
if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFERED FAILED"
fi
